bases:
  nmme:
    models:
      - multimodel
      - canesm5
      - ccsm4
      - cesm1
      - cfsv2
      - gem52nemo
      - geos5v2
      - spear
      - bam12

  copernicus:
    models:
      - multimodel
      - ecmwf
      - ukmo
      - meteo_france
      - dwd
      - cmcc
      - ncep
      - jma
      - eccc4
      - eccc5
      - bom
      - bam12

variables:
  - prec
  - t2mt

calibrations:
  - regr
  - cox
  - nocalib